# Generated by Django 2.1.5 on 2019-02-18 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_account_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_account_id', models.CharField(max_length=100)),
                ('p_account_owner', models.CharField(max_length=50, null=True)),
                ('p_amount', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('p_category', models.TextField(null=True)),
                ('p_category_id', models.IntegerField(null=True)),
                ('p_date', models.DateTimeField(null=True)),
                ('p_iso_currency_code', models.CharField(default='USD', max_length=5)),
                ('p_location_address', models.CharField(max_length=50, null=True)),
                ('p_location_city', models.CharField(max_length=50, null=True)),
                ('p_location_lat', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('p_location_lon', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('p_location_state', models.CharField(max_length=10, null=True)),
                ('p_location_store_number', models.CharField(max_length=10, null=True)),
                ('p_location_zip', models.CharField(max_length=10, null=True)),
                ('p_name', models.CharField(max_length=100, null=True)),
                ('p_payment_meta_by_order_of', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_payee', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_payer', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_payment_method', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_payment_processor', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_ppd_id', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_reason', models.CharField(max_length=50, null=True)),
                ('p_payment_meta_reference_number', models.CharField(max_length=50, null=True)),
                ('p_pending', models.BooleanField(default=False)),
                ('p_pending_transaction_id', models.CharField(max_length=100, null=True)),
                ('p_transaction_id', models.CharField(max_length=100, null=True)),
                ('p_transaction_type', models.CharField(max_length=50, null=True)),
                ('p_unofficial_currency_code', models.CharField(max_length=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_account_id', models.CharField(max_length=100)),
                ('p_account_balance_available', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('p_account_balance_current', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('p_account_balance_iso_currency_code', models.CharField(default='USD', max_length=5)),
                ('p_account_balance_limit', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('p_account_balance_unofficial_currency_code', models.CharField(max_length=5, null=True)),
                ('p_account_mask', models.CharField(max_length=5, null=True)),
                ('p_account_name', models.CharField(max_length=100, null=True)),
                ('p_account_official_name', models.CharField(max_length=200, null=True)),
                ('p_account_subtype', models.CharField(max_length=20, null=True)),
                ('p_account_type', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_access_token', models.CharField(max_length=100)),
                ('p_item_id', models.CharField(max_length=100)),
                ('p_institution_id', models.CharField(max_length=20)),
                ('p_item_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('past_tokens', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item_accounts',
            name='items_id',
            field=models.ForeignKey(db_column='items_id', on_delete=django.db.models.deletion.CASCADE, to='fin.Items'),
        ),
        migrations.AddField(
            model_name='item_account_transactions',
            name='item_accounts_id',
            field=models.ForeignKey(db_column='item_accounts_id', on_delete=django.db.models.deletion.CASCADE, to='fin.Item_accounts'),
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('user_id', 'p_institution_id')},
        ),
        migrations.AlterUniqueTogether(
            name='item_accounts',
            unique_together={('items_id', 'p_account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='item_account_transactions',
            unique_together={('item_accounts_id', 'p_transaction_id')},
        ),
    ]
